# Generated by Django 5.0.7 on 2024-07-25 12:55

import datetime
import django.db.models.deletion
import store_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_charge', models.CharField(blank=True, max_length=120, null=True, verbose_name='Une Charge')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nom Article')),
                ('description', models.TextField(blank=True, max_length=15000, null=True, verbose_name='Description Article')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('cree_le', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Cree le')),
                ('vendu', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vendu')),
                ('image_charge', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[store_app.models.validate_file_extension], verbose_name='Article chargé')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaireCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('image_charge', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[store_app.models.validate_file_extension], verbose_name='Fichier de charge')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.charge')),
            ],
        ),
    ]
