# Generated by Django 5.0.7 on 2024-07-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_charge_formulairearticle_formulairecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairearticle',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.category'),
        ),
    ]
