# Generated by Django 5.0.7 on 2024-08-17 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_about_alter_formulairearticle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=120, null=True, verbose_name='Prenom')),
                ('tel', models.CharField(blank=True, max_length=120, null=True, verbose_name='Tel')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('addresse', models.TextField(blank=True, max_length=15000, null=True, verbose_name='Addresse')),
                ('description', models.TextField(blank=True, max_length=15000, null=True, verbose_name='Description')),
                ('cree_le', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Cree le')),
            ],
        ),
    ]
