# Generated by Django 5.0.7 on 2024-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_formulaireclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairearticle',
            name='ref_article',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Référence Article'),
        ),
    ]
