# Generated by Django 5.0.7 on 2024-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_formulairearticle_ref_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairearticle',
            name='ref_article',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence Article'),
        ),
    ]
