# Generated by Django 5.0.7 on 2024-08-25 12:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_formulairecharge_description_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairearticle',
            name='quantite_article',
            field=models.IntegerField(default=0, verbose_name='Quantité Disponible des Article'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantite_product',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qantité article'),
        ),
        migrations.AlterField(
            model_name='formulairearticle',
            name='vendu',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Vendu'),
        ),
        migrations.CreateModel(
            name='FormulaireVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vente', models.PositiveIntegerField(default=0, verbose_name='Quantité Vente')),
                ('date_vente', models.DateTimeField(blank=True, null=True, verbose_name='Date Vente')),
                ('description_vente', models.TextField(blank=True, max_length=15000, null=True, verbose_name='Description Vente')),
                ('category_vente', models.CharField(blank=True, max_length=120, null=True, verbose_name='Category Vente')),
                ('cout_revient_total_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Coût revient Total Vente')),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Prix Estimé')),
                ('etat_vente', models.CharField(blank=True, choices=[('Vendu', 'Vendu'), ('Commande', 'Commande')], max_length=120, null=True, verbose_name='Etat Vente')),
                ('etat_livrer', models.CharField(blank=True, choices=[('Livrer', 'Livrer'), ('En_instance_de_livraison', 'En instance de livraison')], max_length=120, null=True, verbose_name='Etat Livraison')),
                ('etat_payer', models.CharField(blank=True, choices=[('Payer', 'Payer'), ('En_instance_de_payement', 'En instance de payement')], max_length=120, null=True, verbose_name='Etat Payement')),
                ('etat_final', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Espece', 'Espece'), ('Virement', 'Virement')], max_length=120, null=True, verbose_name='Etat Final')),
                ('hidden_vendu_vente', models.BooleanField(default=False, verbose_name='Vente Vendu?')),
                ('marge_pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Marge %')),
                ('marge_chifre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Marge En Chifre')),
                ('cree_le', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Cree le')),
                ('article_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.formulairearticle')),
                ('client_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.formulaireclient')),
            ],
        ),
    ]
