# Generated by Django 5.0.7 on 2024-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
